# Generated by Django 3.2.13 on 2022-05-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensehatReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sensehat_sensor', models.IntegerField(choices=[(0, 'temperature')], default=0)),
                ('reading', models.CharField(max_length=10)),
                ('source', models.IntegerField(choices=[(0, 'MQTT'), (1, 'Websocket')])),
            ],
        ),
    ]
